### PR TITLE
Override LLVM version in GHA workflow

### PR DESCRIPTION
**Pull request by nightlark**
Adds an option to override the LLVM version pulled and built as part of a GHA workflow run.

### CODE REVIEW

**Comment by henryiii** [comment]
Shouldn't this be pulled from setup.py too? Otherwise these will be out of sync.

**Comment by nightlark** [comment]
Updating the version in setup.py is something that should be done, but I think there is some complexity because the version in setup.py is slightly decoupled from the LLVM version to pull due to the possibility of a post-release segment or a 4th dotted version number getting added for pip package change that don't affect the clang-format version.

I think the main time the version in setup.py becomes relevant is when publishing the wheels so I was thinking versioneer and tags/publishing releases on GitHub for the main way new versions are released on PyPI, and then for old clang-format versions or special case releases another workflow input that takes a wheel version number could override the version in setup.py and trigger a push to PyPI.

**Comment by nightlark** [comment]
setuptools_scm looks interesting, I'll try it out; the main thing with it (and versioneer) seems to be how to override the version it gets from the last git tag... which could just making a local tag right right before building the wheels.

Maybe stripping the first three numbers and any `-*` prefix to enable building LLVM pre-releases?

**Comment by henryiii** [comment]
SETUPTOOLS_SCM_PRETEND_VERSION [example](https://github.com/scikit-hep/boost-histogram/blob/71cc2baf2dc9b7263f4a03313fd194cd1f76d33b/.github/workflows/wheels.yml#L25-L26)?

**Comment by dokempf** [comment]
This looks good to me as is. I will address the part with picking up the correct version in `setup.py` soon. I will have a look at `setuptools_scm` (I looked at versioneer before and decided not to use it). However, the with the LLVM releases frequency being quite moderate, I am not planning to build too much automation logic, because I will very likely spend more time maintaining that logic than bumping versions every few months.

**Pull request merged**
